import type { Metadata } from "next";
import Navbar from '../app/components/Navbar/Navbar'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "NFT Tailwind Template",
  description: "Generated by create next app",
  icons: '/favicon.ico',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      
      <body className={inter.className}> <Navbar/>{children}</body>
    </html>
  );
}
